### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by 41john** [pigskin/kodi-gamepass#397] opened 2018-09-04 13:09 UTC
Hi guys, I run the Gamepass channel for Plex. Just wondering if you have been seeing some login issues recently with this addon?

Looks like the service is authenticating using Gigya now?

**Comment by aqw** [comment] 2018-09-04 13:18
@41john I've been doing a lot of work recently with the pigskin lib, and I've be running into intermittent problems with their login. I'm not sure if I'm being temporarily banned for too many retries, if their service is having problems, or if they're making changes. But yeah, it's odd.

Have you dug into this at all?

**Comment by 41john** [comment] 2018-09-04 13:26
Glad it ain't just me, though sucks to have these issues at the start of the season!

I have looked at it a bit when I have had the small bit of time to do so. If you capture your web session when logging in on the gamepass site you will see that it now goes to a service provider gigya to auth and then auth's slightly differently afterwards to the gamepass api. I'm yet to fully work on providing a solution. Looking at what happens when it auth's with the gigya provider it seems doable to recreate this but could be tricky. I was able to POST to gigya and get a successful auth however I need to work out where one or two variables are coming from the make this a working solution

**Comment by aqw** [comment] 2018-09-04 13:29
@41john They always break it, right about now. Very annoying.

I'm looking at the web app, and it's a little odd. I think they're just dropping this in, hard-coding it into the web-ui rather than returning this login target as part of their normal config API.

I don't have a ton of time either right now, but if I get it working, I'll be sure to give you a heads up. Otherwise, this will have to wait a few days for me.

---Alex

**Comment by kaileu** [comment] 2018-09-04 13:46
It is just the web app or the mobile apps also?
On my Phone there is still no evidence that there is changed something.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment] 2018-09-04 14:14
@kaileu No idea about the mobile app, but the web is (at least for now) using gigya. There's a flag for whether it funnels to gigya or not. Don't know if the old one is shutdown permanently now or what.

**Comment by 41john** [comment] 2018-09-04 14:47
I will test mobile this evening, I’m hoping this is an option. Will also test my Apple TV. Otherwise we need to get it working via gigya.

**Comment by aqw** [comment] 2018-09-04 18:58
@41john Interesting. Thanks for sharing this! Your ``GIGYA_AUTH`` was the key bit I was missing. I'm a bit miffed that they don't share it via their JSON API, but whatever.

I'll let you know once I've made the fix, and if I uncover anything else in the process. :-)

---Alex

**Comment by 41john** [comment] 2018-09-04 19:03
You are welcome, seems to work great in my Plex channel now.

**Comment by aqw** [comment] 2018-09-05 07:06
@41john I can confirm that this works locally for me. I ran out of time, so it's not pushed yet (will happen Friday), but it does work. 

Thanks again for for your help. :-)

**Comment by aqw** [comment] 2018-09-08 13:10
@41john Just as FYI, I have implemented your fix in pigskin. aqw/pigskin@b9b9f947ec77304fcef2ee0ac18ac2299feaa7f0
My implementation is largely the same as yours. The main differences are that I chose to stick with ``password`` as the ``grant_type`` rather than switching to ``shield_authentication``, and my acquisition of the gigaya API key should be a bit more resilient (urlparse would be the complete solution here, but it felt like overkill).

Thanks again for your help. :-)

---Alex

**Comment by aqw** [comment] 2018-09-08 18:11
The fix has been cherry-picked in 6d84f4d896baac06a7a243abc7073af43e47db13

Closing

**Comment by kaileu** [comment] 2018-09-08 18:15
I am still confused that i don‘t habe any login Problems 🤔
Its wierd.

**Comment by aqw** [comment] 2018-09-08 18:41
@kaileu I'm confused that you're confused. Are you running the latest code? If so, you have the necessary fixes.

if you don't have the latest code, then perhaps Game Pass re-enabled the old auth method. They've been toggling the Gigya requirement on and off. I have no idea what the heck they're doing.

**Comment by kaileu** [comment] 2018-09-08 19:05
no my code base was not touched since 3 weeks.
odd behaviour maybe it is more a regional thing.

not to mention that gygia is against europe dsgvo because they have to tell if they switch login provider and transfer the whole login detail to another company....

**Comment by Ghoschdi** [comment] 2018-09-09 21:09
The old version from the kodi repo (August 23rd) works for me, the new version from git not. Get tons of login errors. Only downside, i seem unable to play any live games as I cannot open the week 1 category since 10pm CET. https://github.com/aqw/xbmc-gamepass/issues/396

**Comment by aqw** [comment] 2018-09-10 05:27
@Ghoschdi @kaileu Thanks for the info. Sounds like the authentication isn't uniform everywhere. I now of reports of only 2018.08.23 working for some people and only 2018.09.08 working for others.

So I think the logging really should be sniffing for access, and then trying different auth methods from there. I'll try to make these changes soon, so people can start testing them.

**Comment by aqw** [comment] 2018-09-10 14:07
Ok, so I've taken a bit of a brute force approach to the authentication code. The code now does the following:
- check if it's already authenticated (to avoid being banned by gigya)
- authenticate directly against Game Pass (the old auth method)
- if that fails, authenticate to the Gigya servers, get those keys, and login to the Game Pass servers using the Gigya keys.

This "should" work for everyone. But I won't be surprised in the least if it all blows up.

Any and all testing of this is /much/ appreciated. :-)

**Comment by tinzarian** [comment] 2018-09-10 15:31
Login seems ok now. I had login issues with both the repo version (0823) end the latest master. With these changes I can login again.

**Comment by Ghoschdi** [comment] 2018-09-11 10:50
Sorry, abroad at the moment and can only test Sunday this week. That said, my big problem was not login but the issue of not being able to open the week 1 category. Should I create another issue Sunday if it happens again?

________________________________
Von: Alex Waite <notifications@github.com>
Gesendet: Tuesday, September 11, 2018 9:30:18 AM
An: aqw/xbmc-gamepass
Cc: Stefan Denz; Mention
Betreff: Re: [aqw/xbmc-gamepass] Login Issues (#397)


@tinzarian<https://github.com/tinzarian> Fantastic. Thanks for the info. @Ghoschdi<https://github.com/Ghoschdi> and @kaileu<https://github.com/kaileu> Does the latest code work for you too?

**Comment by aqw** [comment] 2018-09-11 20:32
@Ghoschdi No problem. :-)

Yeah, if you have problems with entering a week again, please do open an issue. I'll see if I can take a look at it then.

**Comment by atduke** [comment] 2018-09-19 16:58
The 0823 version was working for me until yesterday evening. When logins started failing today, I upgraded to Git master. Login is ok again, but I can't stream any games. Only related error:

`18:36:16.307 T:1155523328   ERROR: could not find GP tokens to refresh`

I added some logging code in refresh_tokens(), the response from https://www.nflgamepass.com/api/user/oauth/token is:

```
{
  'validationErrors': None,
  'message': 'error_unauthorised',
  'code': 'UR_10006',
  'id': 'some long id',
  'httpStatusCode': 401
}
```

I tried the App and Website too, both work.

Cheers.

**Comment by rschloeg** [comment] 2018-09-19 18:57
Pretty much the same for me. Today, I can not start a new stream and get the same error
20:37:39.150 T:1761604512   ERROR: could not find GP tokens to refresh 
I have the latest version installed. Yesterday it worked. Maybe the NFL did make change?

**Comment by atduke** [comment] 2018-09-22 12:54
It seems logins are possible again with the 0823 version, so i downgraded and applied the fix discussed in #410 . Works for the time being.

**Comment by Displayel** [comment] 2018-10-22 19:08
the login issues are back for me on kodi, anyone else having problems loging in ?

**Comment by Displayel** [comment] 2018-10-23 13:52
well it used to work but without changing anything on the configuration its not working anymore, its not a problem to being logged in somewhere else because you can connect up to 5 times starting this season...when you say you use the latest version is it here from github or is it just the latest version via repo ?

**Comment by Ghoschdi** [comment] 2018-10-23 16:29
Latest master (github), works really flawless.
And good to know that 5 times thing, but it seems to be really bugged then. If i log into the webapp, i need to wait quite a while before i can login on Shield TV with the Kodi GP addon.

**Comment by MiranDalic** [comment] 2018-10-27 13:46
> Just download the latest master from here: https://github.com/aqw/xbmc-gamepass/archive/master.zip put it onto a USB or transfer it somehow to your system that has Kodi, jump into Kodi, go to addons, select install from zip and select the package you downloaded. It will update the plugin and then work out of the box

Installed and logon works, but "game video" does not work :/ "coach film" does not, so only I can start Condensed game and highlights :/

**Comment by Ghoschdi** [comment] 2018-10-30 17:44
> Installed and logon works, but "game video" does not work :/ "coach film" does not, so only I can start Condensed game and highlights :/

I just tested this with the SEA at DET game and all 4 formats work flawlessly. Do you use the inputstream adaptive version? If not, i would give it a shot.

**Comment by MiranDalic** [comment] 2018-11-02 22:12
> > Installed and logon works, but "game video" does not work :/ "coach film" does not, so only I can start Condensed game and highlights :/
> 
> I just tested this with the SEA at DET game and all 4 formats work flawlessly. Do you use the inputstream adaptive version? If not, i would give it a shot.

By default was the best quality not adaptive. I did try it adaptive but nothing change. Maybe you have older version of Kodi ?

**Comment by Ghoschdi** [comment] 2018-11-03 16:41
I have the last stable release of 17.6 from Play store and on Windows, both work w/o any issues and both using inputstream adaptive. Have you activated the Kodi addon for that before enabling it on the GP addon? Because you will not see any quality selection when you use it, so no to your first sentence.

**Comment by MiranDalic** [comment] 2018-11-04 09:48
> I have the last stable release of 17.6 from Play store and on Windows, both work w/o any issues and both using inputstream adaptive. Have you activated the Kodi addon for that before enabling it on the GP addon? Because you will not see any quality selection when you use it, so no to your first sentence.



> I have the last stable release of 17.6 from Play store and on Windows, both work w/o any issues and both using inputstream adaptive. Have you activated the Kodi addon for that before enabling it on the GP addon? Because you will not see any quality selection when you use it, so no to your first sentence.

I saw those settings and was thinking that they enabled. IMO having odd logic to set on/off and I was thinking that they are set ON. Apparently they aren't... After they were set ON all works like charm. I would like to thank to all people who make this add on it is so much better to use and control Gamepass trough remote and smart TV instead NFL app trough smartphone. Also I would like to thank you for help too !

**Comment by Ghoschdi** [comment] 2018-11-04 10:58
So in reverse that means that without inputstream adaptive playback of game & coach video is broken. Will test that later myself and if true, will open a new issue here.

**Comment by jm-duke** [comment] 2022-04-25 20:50
Doing some clean-up and this issue report is really old, so I'm closing it.

**Closed by jm-duke** 2022-04-25 20:50 UTC
