### ISSUE TITLE
Can't play any stream "No active NFL Game Pass Europe subscription was found"

### ISSUE THREAD

**Issue by jbarry786** [pigskin/kodi-gamepass#443] opened 2022-08-23 21:47 UTC
EDIT: simplified this opening post to make it easier to read (the first replies below were in response to a longer version of the post)

----
Hey everyone,

I just can't seem to get the addon to work.  

**Kodi 19.1 Log:** https://paste.kodi.tv/paseqoyibo.kodi

I imagine I must be missing something 'obvious' here, otherwise I'd see similar issues reported. Can anyone have a look and suggest what may be the issue?

Thanks in advance.

P.S: I've also tried on Kodi 20 (I understand that in this case it may not be supported yet), here's a short version of the log on the PC: https://paste.kodi.tv/jizakenuba.kodi

**Comment by jm-duke** [comment] 2022-08-24 21:06
Hi,

well, this error is kinda misleading.

1) Gamepass Europe is Gamepass International nowadays. I'll update the error message.

2) The add-on uses the subscription check to verify, if a session was already established and a login is not required. If you were not authenticated previously, the subscription check fails and this error is logged. I should probably look into this as well.

In your case, the real problem I think is this:

`2022-08-23 20:52:30.015 T:9653    DEBUG <general>: [script.video.nfl.gamepass] script.video.nfl.gamepass: InputStream Adaptive is not installed and/or enabled.`
`2022-08-23 20:52:30.020 T:9653    DEBUG <general>: [script.video.nfl.gamepass] script.video.nfl.gamepass: Disabling InputStream Adaptive.
`

That would be a dupe of #437 .

Please try installing the InputStream Adaptive addon and enable "Use InputStream Adaptive" in the addon settings.

Hth,
Duke.

**Comment by jbarry786** [comment] 2022-08-24 22:56
Hi @jm-duke 

Thanks for the reply. I appreciate it.

I was aware after reading the issues here that inputstream needs to be active. I guess that log had the history when it wasn't enabled. But if you check the full log (just search for "creating inputstream"), you can can see that Inputstaream is installed/active and this error shows up:

"2022-08-23 20:52:40.637 T:9664     INFO <general>: Creating InputStream
2022-08-23 20:52:40.642 T:9597    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Connection: keep-alive'
2022-08-23 20:52:40.642 T:9664    DEBUG <general>: Skipped 1 duplicate messages..
2022-08-23 20:52:40.642 T:9664    DEBUG <general>: CurlFile::Open(0xba755b58) https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3
2022-08-23 20:52:40.642 T:9664    DEBUG <general>: easy_acquire - Created session to https://vod-i-main-nflusvideo.akamaized.net
2022-08-23 20:52:40.646 T:9633    DEBUG <general>: Loading settings for https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3|Connection=keep-alive&User-Agent=Firefox|Connection=keep-alive&User-Agent=Firefox
2022-08-23 20:52:40.777 T:9597    ERROR <general>: CCurlFile::Exists - Failed: HTTP returned error 403 for https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)/VIDEO_TS.IFO?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3|Connection=keep-alive&User-Agent=Firefox|Connection=keep-alive&User-Agent=Firefox
2022-08-23 20:52:40.779 T:9597    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'Connection: keep-alive'
2022-08-23 20:52:40.791 T:9664    ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2022-08-23 20:52:40.791 T:9664    ERROR <general>: CCurlFile::Open failed with code 403 for https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3:
             "

**Let me upload a fresh Kodi log that should just show me trying to play the streams:** 

[kodi_THOMAS.log](https://github.com/pigskin/kodi-gamepass/files/9419885/kodi_THOMAS.log)

Besides the 403 error, we can also see this:

2022-08-23 22:42:13.752 T:17156   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SystemExit'>
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.video.nfl.gamepass\default.py", line 611, in onClick
                                                       self.play_url(stream_url)
                                                     File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.video.nfl.gamepass\default.py", line 462, in play_url
                                                       xbmc.sleep(100)
                                                   SystemExit
                                                   -->End of Python script error report<--
                                                
----------------------

Thanks again for the feedback: I've tried on different devices and even fresh installs. It's quite confusing.

**Comment by ohhmyy** [comment] 2022-08-25 18:42
Hi @jbarry786 . Out of curiosity I installed the addon under Kodi 20 and got the same error as you. I don't know if the addon is supposed to work with Nexus at all though.

With Kodi 19 the addon runs with no problems (inputstream.adaptive activated in Kodi + activated in Game Pass addon).
Is your 403 error with Kodi 19? I can force this error only with deactivating inputstream.adaptive in the Game Pass addon, so make sure that it is activated there.

**Comment by jbarry786** [comment] 2022-08-25 20:02
Hey @ohhmyy , thanks for the reply. My issue happens on Kodi 19 as well. 

This is a log of the add-on, Kodi 19.1 with inputstream v3.0.1. 

Tested just now:

https://paste.kodi.tv/paseqoyibo.kodi

Fails to open the manifest file, 403 error. My opening post above has attached a full debug log from the other day that shows the same:

**CCurlFile::Stat - Failed: HTTP response code said error(22) for** https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3|Connection=keep-alive&User-Agent=Firefox|Connection=keep-alive&User-Agent=Firefox

----
2022-08-23 20:52:40.929 T:9664    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [https://vod-i-main-nflusvideo.akamaized.net/vodus/541a74db-c811-4f6f-8761-e1150668029c/NoAds_BAL_ARI_1080_pre2.ism/exp=1661327560~acl=%2f*~data=hdntl,fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=3fe80c5516f940b38774ea8ecc0804fb51eedda69f42a802f0068339a29e1181/QualityLevels(5988733)/Manifest(video,format=m3u8-aapl-v3,audiotrack=aac_UND_2_128,filter=chromecast)?hdnea=st=1661284269~exp=1661284449~acl=/vodus/541a74db-c811-4f6f-8761-e1150668029c/*~data=fe2d2b76-8bfc-4690-becd-fa150ca2922c~hmac=4ff979661d9384efa16192f33f6f94298fa900d90bc094b87aaac46aa1b26e9d&hdcore=2.11.3|Connection=keep-alive&User-Agent=Firefox|Connection=keep-alive&User-Agent=Firefox]

---

I do notice that the manifest files the addon shows are different from the ones I see on the website, but I imagine that's the way it's coded.

Do you or @jm-duke have any ideas of what may be causing this 403 error? 

It feels super bizarre since this appears to be something specific with me.

Thanks again for the feedback.

**Comment by ohhmyy** [comment] 2022-08-28 18:59
Hi @jbarry786 . According to the log you posted, **inputstream.adaptive** is missing from your installation:
![Unbenanntiput](https://user-images.githubusercontent.com/88911468/187090302-a9fedfd0-98dd-498b-a901-396a4f6ee59f.png)

**Comment by jbarry786** [comment] 2022-08-28 19:02
Hey @ohhmyy , isnt this inputstream?

![image](https://user-images.githubusercontent.com/30951795/187090387-eb4b1631-8e38-41df-8e46-d58a04524aa1.png)

**Comment by jbarry786** [comment] 2022-08-28 19:28
@ohhmyy that is it. Of course it had to be something 'obvious'.

Thanks for looking into it.

**Closed** 2022-08-28 19:28 UTC
