### ISSUE TITLE
Resume of extended pause of Live Stream skips forward to live

### ISSUE THREAD

**Issue by alexanderritola** [pigskin/kodi-gamepass#28] opened 2013-09-15 18:08 UTC
I couldn't find anything in the README.md or issues about this, so I'm not sure if the issue is specific to me or if it just hasn't effected anyone yet.

System is Xubuntu 13.04 and running the most recent Gotham build from ppa:team-xbmc/unstable. 

Pausing for brief periods of time doesn't seem to cause any problem. However, after being paused for 38 minutes, when I resumed it skipped forward to live. I haven't been able get rewind to work at all and fast-forwarding is glitchy. One issue I had with fast-forward seems to be that it's possible to fast-forward beyond live, which forced me to wait for live to "catch-up" since rewind won't work for me.

Let me know if any additional information is needed.

I'd just like to add that I fully understand that this is alpha software and in no way am I complaining. Thank you and great work!

**Comment by BaumSchorle** [comment] 2015-05-25 09:18
Hey guys,

I came across the NHL-GameCenter plugin. GameCenter is also hosted bei Neulion, so the technology could be the same or at least close.

The developper of this plugin, created some kind of HLS Proxy to start the game from the beginning. I just had a brief look but it looks like, this service is creating its own playlist.

Here is a link to the git repository: https://github.com/timewasted/service.nhl-hls-proxy

Maybe @timewasted can assist us with this and if this fits our needs, it would be great if we could use this service. 

Raffael

**Comment by timewasted** [comment] 2015-05-27 01:42
Heh, my brother keeps telling me that I should try to get involved in this add-on.

I'm not sure if the HLS proxy will actually do anything for this issue.  You're correct in that it creates its own playlist.  The proxy is given a time to rewind to (typically the start of the game, but can be anything), and fetches a "live" playlist (which contains I believe 6 segments of video).  The video segments are named by timestamp, and the playlist says how long each segment is.  So, it's pretty simple to rewind to the proper time.  Then it just builds a playlist that's X minutes long (currently set to 6 hours) and feeds that to Kodi.

What I had originally wanted to do was just rewind to the desired time, and provide a playlist that extends from start_time to current_time.  Unfortunately, when given a non-complete ("live") playlist, ffmpeg will just start at the 3rd to last segment in the list.  I saw no way to change that functionality, so I just decided to go with the brute-force method of making a really long playlist and hope that "really long" ends up being long enough.

Now that you've got me thinking about it, I wonder if it actually would fix the issue.  I have to imagine that the issue is that Kodi gets a playlist for segments 1-6, something happens that prevents the playlist from refreshing (network issue, for example), then the next playlist refresh lists segments 12-18.  With a "complete" playlist, there's no need to refresh it, so it won't ever skip segments.  It's very far from an elegant solution (for example, skipping past live results in Kodi just saying "nope" and stopping playback), but maybe it's acceptable?

**Comment by Alexqw** [comment] 2015-05-27 07:18
> my brother keeps telling me that I should try to get involved in this add-on.

Then he's a wise man. ;-) We're always happy for more contributors.

I'm currently on vacation for 2 weeks, so I havn't taken the time yet
to even look at the repo that @BaumSchorle linked to.

> What I had originally wanted to do was just rewind to the desired time, and provide a playlist that extends from start_time to current_time.

In general, this is the solution I'd prefer. A proxy seems to be a
heavy-handed approach.

> Unfortunately, when given a non-complete ("live") playlist, ffmpeg will just start at the 3rd to last segment in the list.

This sounds like an ffmpeg bug. If you can reproduce it when using
ffmpeg directly, then I suggest posting to their mailing list and see
if they have any ideas.

> I have to imagine that the issue is that Kodi gets a playlist for segments 1-6, something happens that prevents the playlist from refreshing (network issue, for example), then the next playlist refresh lists segments 12-18. With a "complete" playlist, there's no need to refresh it, so it won't ever skip segments. It's very far from an elegant solution (for example, skipping past live results in Kodi just saying "nope" and stopping playback), but maybe it's acceptable?

I wonder/suspect that m3u8 already has a concept for live streams that
have an undefined termination time. I suggest checking if there's a
spec, and then see if it's possible to marry the stream info we get
from NeuLion with ffmpeg's understanding of the m3u8 spec. If we're
lucky, then it will resolve all of the above problems. :-)

When I'm back from vacation, I'll take a closer look at this.
@BaumSchorle also has commit access, so if you convince him of your
fix, then he can merge it for you.

Thanks for getting involved!

---Alex

**Comment by timewasted** [comment] 2015-05-27 16:40
So, this is interesting.  When I wrote the HLS proxy, I did so because after looking through ffmpeg sources, I found that the "start from the 3rd to last segment" behavior was explicitly coded.  Your response prompted me to find that section of code again, but... it's not there any more.  I checked the revision history for the file, and [found this gem](http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=bcf44c91c30940822bd8bcd612c2a5ab0a3440f2):

```
libavformat/hls: add an option to start from a given segment in a live stream
```

So it **did** prefer to start at the 3rd to last segment until March 28th of this year.  The good news is that that opens up possibilities.  The bad news is that I'm not sure if it even remotely matters, for a couple of reasons.  The first is that Kodi 15 says it ships with ffmpeg 2.6.2, and I don't see that commit listed in the 2.6.2 release.  It IS possible that I'm missing something, however, since I don't actually see it listed in ANY release so far.  The second is that even if the version of ffmpeg that ships with Kodi supports it, I don't know that Kodi actually offers any way to dig into the internals of ffmpeg in order to control that.

[The HLS spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-13) does cover how to handle live streams of an indeterminate length.  It basically says "you need to keep refreshing the playlist until you hit the endlist tag, then stop".  Unfortunately, that's not really helpful to us.  At least for the hockey playlist, there are HOURS of "this game will begin shortly"/"this game has ended" before/after the actual game.

Trying to figure this all out has caused me a great number of headaches, which is why I just ended up saying "screw it, I'm going with a proxy!"  You don't even want to get me started on the best way to pre-load X number of video segments to try to limit the annoying "Buffering..." stops during playback...!

**Comment by kaileu** [comment] 2015-05-27 17:04
"At least for the hockey playlist, there are HOURS of "this game will begin shortly"/"this game has ended" before/after the actual game."

The same behaviour has the nfl streams.

Mit freundlichen Grüßen
Kai Leutner

**Comment by subx25** [comment] 2017-09-15 20:24
Time to dig up this issue again...

In previous years, navigating a live stream was only available in the Flash player, but with the change of provider, it's now available to all. So is it now possible to bring this feature to Kodi?

**Comment by kaileu** [comment] 2017-09-15 20:29
I don't thinks its possible without proxy the ts files. If Kodi or Inputstream implements the latest m3u8 standard this feature could be implemented. But for now as i see its not implemented and so its not possible with a player which follow the m3u8 3.0 Standard.

Mit freundlichen Grüßen
Kai Leutner

**Comment by subx25** [comment] 2017-09-18 19:37
Ah I didn't realise there was a Kodi limitation too. Anyone asked the [m3u8](https://github.com/globocom/m3u8) guys if they could help out?

**Comment by kaileu** [comment] 2017-09-18 19:49
The Problem is not the parsing. (And the people you references are only for parsing not playing)
You have to tell Kodi where to play the Game. With a player that works like the rfc is called live events has to play a maximum of 4 lines before the end of the list.

So everytime you pause a game and restart playing, the player will maximum delay 4 lines  at the end of the list.

With the current m3u8 draft aka http live streaming there is a possibility to tell when exactly start a game. But this isn't build inside Kodi as far as i noticed it.

The only hardcoded Solution for now would be to rewrite the event type. But this is nothing for the whole community or at least needs some extended testing.

Mit freundlichen Grüßen
Kai Leutner

**Comment by jm-duke** [comment] 2022-04-25 20:38
Doing some clean-up and this bug report is really old, so I'm closing it.

**Closed by jm-duke** 2022-04-25 20:38 UTC
Labels: bug
