### ISSUE TITLE
Error when trying to start a stream

### ISSUE THREAD

**Issue by rschloeg** [pigskin/kodi-gamepass#410] opened 2018-09-20 19:11 UTC
Like already commented in #397 by atduke and me:
Since Yesterday, I can not start a new stream and get an error message. The Kodi logfile shows the error message
20:37:39.150 T:1761604512 ERROR: could not find GP tokens to refresh
I have the latest version installed. The day before it worked fine. 

[kodi.log](https://github.com/aqw/xbmc-gamepass/files/2402725/kodi.log)

**Comment by ttobsen** [comment] 2018-09-21 00:19
Same here. Neither Jets vs. Browns nor NFL Network is working.

**Comment by SirScott13** [comment] 2018-09-21 00:50
Same issue.  My error says "Unexpected Error :( Please enable debugging for both the addon and Kodi and submit a bug report."

**Comment by kaileu** [comment] 2018-09-21 05:06
My guess is its related to https://github.com/aqw/pigskin/pull/23

**Comment by rschloeg** [comment] 2018-09-21 16:46
@kaileu As far as I understand you mean we should try the newest version of the pigskin library. But how can we install that one? Up to now pigskin is part of the gamepass package, but the newest build of that is much older than the newest version of pigskin.

**Comment by kaileu** [comment] 2018-09-21 17:06
No i only send a pull request.
Alex has to merge the code till its in the official package.
You could look what i changed and change it in your addon.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Ghoschdi** [comment] 2018-09-21 18:10
Hi Kai, 

thanks for this, but unfortunately just combining your changes with the latest Github version if the Game Pass addon does not fix the issue (at least for me)

**Comment by kaileu** [comment] 2018-09-21 18:15
I am using still the old version which works for me:(
I didn‘t have time at the moment to review all the changes from alex maybe there is also something else wrong

**Comment by Ghoschdi** [comment] 2018-09-21 18:32
So you are saying you are using the old release and combined it with your tweaks? Will test that right away

**Comment by Ghoschdi** [comment] 2018-09-21 18:40
I can approve. Grabbing the old repo version or the master from Kaileu's github here: https://github.com/kaileu/xbmc-gamepass + editing the \resources\lib\pigskin.py in the zip archive 
Line 349:  `vs_format = i.attrib['format'].lower() to  vs_format = i.attrib['name'].lower()` will get the playback working again.

**Comment by rschloeg** [comment] 2018-09-21 19:27
I can confirm that. It works for me, too. Thank you very much, @kaileu and @Ghoschdi !
The only difference for me was that in my pigskin.py the line to be changed was line 307. but luckily there is only one line in the script which fits to the description of @Ghoschdi

**Comment by acrewe** [comment] 2018-09-22 12:14
Ah.... after checking repo, master and older versions with and without the 'format' to 'name' fix and receiving the exact same ERROR: Login Failed on each.
Refreshed my IP address; and it's allowed me to login again, so possibly a timing issue or it is an IP ban maybe.

**Comment by atduke** [comment] 2018-09-22 12:51
I too can confirm that after downgrading to 2018.08.23 and implementing the fix provided by @kaileu, I can stream games again.

**Comment by JimmyJones79** [comment] 2018-09-22 16:58
I've tried editing the file on the old version, no luck, tried switching to the 9-8 version, no luck. I wish I had something more to offer than I'm running Kodi 17.6 on a fire TV v2. The add-on worked great on Sunday /Monday, Jets vs Browns was when it failed.

**Comment by fritsie82** [comment] 2018-09-22 19:34
> I can approve. Grabbing the old repo version or the master from Kaileu's github here: https://github.com/kaileu/xbmc-gamepass + editing the \resources\lib\pigskin.py in the zip archive
> Line 349: `vs_format = i.attrib['format'].lower()` to `vs_format = i.attrib['name'].lower()` then installing it in Kodi via the install from zip will get the playback working again.

Works here as well. Not sure what the line number was but found the said text and after installing the zip GamePass worked again on my Kodi.

Edited ZIP file can be found here [https://ufile.io/puxho](url)

**Comment by JimmyJones79** [comment] 2018-09-22 21:58
@fritsie thanks I'll give it a try and report back

**Comment by JimmyJones79** [comment] 2018-09-23 14:39
Are you guys doing anything then, uninstalling game pass, then downloading the 8/23 zip, editing the pigskin.py file, re-zipping and installing the add-on via zipfile method?  Could using Kodi 17.6 Android, ARM be affecting me? I'm at a loss.

**Comment by SirScott13** [comment] 2018-09-23 14:42
@JimmyJones79  
All I did was download the Edited ZIP file that @fritsie82 posted.  Then I installed that add-on via ZIP.  Then when I opened GamePass, full functionality had returned.

**Comment by Ghoschdi** [comment] 2018-09-23 14:44
The failed login problems seems to occur when you logged in to the service on another device or multiple times on the same one. I think they found out that last season you could watch GP on 3 separate devices with 1 account. I believe some of the fixes that @aqw has done in the newer versions address this, but break the functionality of the playback. So i recommend to log out of all devices, do as SirScott said and try in about 15 mins.

**Comment by acrewe** [comment] 2018-09-23 15:01
Got mine working on 1st and 2nd Gen firesticks, so shouldn't be an android/arm issue. To circumvent the login error I was getting, I did have to reboot my router to force a refresh of my IP address as waiting/logging out of everything did not alleviate it.

**Comment by Ghoschdi** [comment] 2018-09-23 15:03
I have a static IP address and can tell you, just logging out of everything and waiting long enough for all sessions to terminate does work.

**Comment by acrewe** [comment] 2018-09-23 15:14
Fair enough, I must have just been impatient

**Comment by Ghoschdi** [comment] 2018-09-23 15:14
> Fair enough, I must have just been impatient

I know that one! :)

**Comment by TweekDash** [comment] 2018-09-24 15:56
Hoping someone can assist. I am having many problems and have tried multiple solutions. I was using the Master branch from https://github.com/aqw/xbmc-gamepass and was able to login but got the errors anytime I would try to start a stream. I went ahead and followed this thread and downloaded the updated file https://ufile.io/puxho which had the edited pigskin.py from Kaileu's master branch. 

When I installed that file I could not login to the app at all looks to be like the login issues from #397 What I tried next was applying the change `vs_format = i.attrib['format'].lower() to vs_format = i.attrib['name'].lower()` here into the aqw master, the login lines used different variables so I replaced the entire For vs from aqe with the For I from the updated kaileu version and I still can't play streams

**Comment by Ghoschdi** [comment] 2018-09-24 16:16
Just sign out of all apps, use the zip file and give the sessions time to terminate. Then try to login again. Until aqw is back or someone from the team can figure out all the clashing changes, there is nothing else you can do (unless you are familiar with python yourself and debug/merge the versions)

**Comment by jpieti** [comment] 2018-09-27 18:01
@fritsie82 zip file worked as a charm! Thank you very much! Also big thanks to people who develop and maintain this NFL game pass addon!

**Comment by laufgas** [comment] 2018-09-28 14:35
What about people like me with Android TV? nothing works on Kodi with my Android TV device. Get an error:  "Unexpected Error :( Please enable debugging for both the addon and Kodi and submit a bug report."

**Comment by jpieti** [comment] 2018-09-28 16:01
Actually I'm using Android TV , too. The only challenge I had, was to figure out how to load the modified zip -file to my Android TV system. My solution was to use my WLAN, which has network hardrive connected. From there it was easy, just install addon from zip file (Kodi showed automatically my network harddrive) and  it started work.

**Comment by laufgas** [comment] 2018-09-28 17:12
@jpieti I don't get an error message now, but when I try to start NFL network or a game, I choose the quality of the stream but nothing happens.

**Comment by laufgas** [comment] 2018-09-28 17:20
One more update: I managed to start Highlights & Condensed games. The rest (NFL Network, full games, coache's film & NFL network archive) dont work.

**Comment by jpieti** [comment] 2018-09-29 14:03
@laufgas In my installation everything works: at least the stuff I need: the games and NFL Network live. Sorry, but I have no clue, why they don't work in your system.

**Comment by jpieti** [comment] 2018-09-29 14:08
@laufgas I don't know, if this has something to do with this... probably not... but I have followed this tip, which helped me earlier:
1. go to add-ons-my Addons
2. VideoPlayer Input Stream
3. Enable input Stream Adaptive
4. Go to gamepass Settings-->display/Video
5. Activate Input Stream Adaptive.
This was because of this: https://forum.kodi.tv/showthread.php?tid=320450&pid=2768126#pid2768126

But like I said, I don't know, if this has anything to do with this.

**Comment by tommmlij** [comment] 2018-10-04 11:45
I never wrote a xbmc addon, but I could not accept that I am not able to watch Drew shredding the record or the shootout between Bortels and the new Uber-QB. So I used my limited knowledge of Python and the Debug Console of Chrome to fix this.

I don't know how robust this is, but it's working for me...

Changes:
https://github.com/tommmlij/xbmc-gamepass/commit/f3cb73a5afa68f2f4bc62a2da9386c7efca44dfa

The zip can be found here:
https://github.com/tommmlij/xbmc-gamepass/releases

Have fun and happy gameday.

**Comment by aqw** [comment] 2018-10-04 11:49
@tommmlij Glad you got this working. I've left a few comments in your repo. If you can do some additional testing, I'll include your changes.

**Comment by kaileu** [comment] 2018-10-04 11:49
If thats your opinion than please make a pull request instead of release an own version.

**Comment by tommmlij** [comment] 2018-10-04 12:59
@kaileu 
That is not my _opinion_, but what I did to make that work for me.
The changes are not tested thoroughly, so I made no pull request. But since the next game is in 11h I made a fork and wanted people to know and potentially make it work. Geeze...

**Comment by jpieti** [comment] 2018-10-04 13:33
@tommmlij Thank you very much! Works great at least in my system!

**Comment by aqw** [comment] 2018-10-04 13:38
I've pushed a version that ports over the latest auth code form pigskin, includes your changes to the post data for gigya auth, adds further guards against exceptions, and includes @kaileu's videoSource fix.

This /should/ work, though no guarantees.

Testing is most welcome.

**Comment by atduke** [comment] 2018-10-04 17:50
Yup, I'm back in business. I installed master and can log-in and stream games again. Thanks to all who contributed!

Cheers!

**Comment by kabukimurder** [comment] 2018-10-04 18:07
Master works great now. Thanks guys!

**Comment by laufgas** [comment] 2018-10-04 19:16
Sorry but I'm abit confused. Which file should I download to test and see if it's working now?

**Comment by ttobsen** [comment] 2018-10-05 00:20
> Sorry but I'm abit confused. Which file should I download to test and see if it's working now?

I think @aqw  means the content of the Master branch. You can easily download the Zip file for installation by choosing the master branch and download the Zip file from the "clone or download" button.

I can also confirm that Master is working smoothly. And I'm pretty sure that games are loading a lot faster now (1-2 seconds compared to felt 5+ seconds in the last versions).

**Comment by Yattle190** [comment] 2018-10-05 12:33
This worked for me too on multiple machines last night but this morning I had the same old "debugging" message when running a stream. 

I cleared my cache in Kodi and now it is working again. So try clearing your cache if you are still having problems with the updated Master. Hope this helps someone.

**Comment by hrym55** [comment] 2018-10-09 08:00
Hi,

I loaded the current master branch and I'm able to login and start condensed and the highlight videos, but unfortunately not the actual game video. I'm allowed to select the bitrate and then nothing happens. In the log there is the following message:

[kodi_short.txt](https://github.com/aqw/xbmc-gamepass/files/2459408/kodi_short.txt)

**Comment by Ghoschdi** [comment] 2018-10-09 08:07
Working flawless for me on both live and replay. 
@hrym55: Can you switch to inputstream adaptive? Look at https://github.com/aqw/xbmc-gamepass/issues/410#issuecomment-425647963 for instructions

**Comment by hrym55** [comment] 2018-10-09 09:14
Oh, I didn't realize this still needs to be done. Now it works. Thank you!

**Comment by JimmyJones79** [comment] 2018-10-14 16:30
@tommmlij thank you. I had it working, then last Sunday it stopped again I was getting the "failed_login" error even though I knew the credentials were correct. So I hooked up my laptop to the TV and watched it that way. Tried again today and still got the failed_login error. Just read that you posted a link to a new file you created and figured give it a try. First time I got a add-on error but I tried again and it works. Thank you.

**Comment by laufgas** [comment] 2018-10-14 18:45
Just wanted to thank you all. Working now. Btw, we can't watch the red zone  channel there?

**Comment by Drunal** [comment] 2019-01-06 00:20
I know its a while, but I can confirm that current master still works, while none of the last two releases does. 
How much effort is it to put a new release out there, just to avoid the search for this topic here?

**Comment by Ghoschdi** [comment] 2019-01-08 08:45
The latest master works flawlessly with the last Kodi 17. release. Cutting a new release is sth the maintainers have to do and since @aqw is very busy with an hefty workload, it might take a while. My gut feeling also says that the next release might bring also compatibility for v18 but that will mean even longer waiting time.

**Comment by jm-duke** [comment] 2022-04-25 20:56
Doing some clean-up and this issue report is really old, so I'm closing it.

**Closed by jm-duke** 2022-04-25 20:56 UTC
